routes:
    home: 'Default:home'
    about: 'Default:about'
    login: 'Security:login'
    logout: 'Security:logout'
    register: 'Security:register'
    editProfile: 'Security:editProfile'
    showProfile: 'Security:showProfile'
    changePassword: 'Security:changePassword'
    changeProfilePic: 'Security:changeProfilePic'
    createArticle: 'Article:createArticle'
    showArticle: 'Article:showArticle'
    editArticle: 'Article:editArticle'
    createComment: 'Comment:createComment'
    deleteComment: 'Comment:deleteComment'
defaut_route: 'home'
db_config:
    name: 'blog_project'
    host: 'localhost'
    user: 'root'
    pass: ''
