routes:
    home: 'Default:home'
    getMarker: 'Default:getMarker'
    admin: 'Default:admin'
    about: 'Default:about'
    blog : 'Default:blog'
    adminLogin: 'Security:adminLogin'
    login: 'Security:login'
    logout: 'Security:logout'
    register: 'Security:register'
    deleteUser: 'Security:deleteUser'
    registerCrafter: 'Security:registerCrafter'
    artisanProfile: 'Security:artisanProfile'
    profile: 'Security:profile'
    editProfile: 'Security:editProfile'
    changeProfilePic: 'Security:changeProfilePic'
    sendMessageTo: 'Message:sendMessageTo'
    startChat: 'Message:startChatTo'
    createArticle: 'Article:createArticle'
    showArticle: 'Article:showArticle'
defaut_route: 'home'
db_config:
    name: 'vill_artisan'
    host: 'localhost'
    user: 'root'
    pass: ''
