routes:
    home: 'Default:home'
    about: 'Default:about'
    blog : 'Default:blog'
    login: 'Security:login'
    logout: 'Security:logout'
    register: 'Security:register'
    artisanProfile: 'Security:artisanProfile'
    profile: 'Security:profile'
    editProfile: 'Security:editProfile'
    changeProfilePic: 'Security:changeProfilePic'
    sendMessageTo: 'Message:sendMessageTo'
    showArticle: 'Article:showArticle'
defaut_route: 'home'
db_config:
    name: 'vill_artisan'
    host: 'localhost'
    user: 'root'
    pass: ''
